# multivariate analysis:

In [1]:
#data cleaning==== removing duplicate values and we are going to treat null values
#feature engineering----->is the process of creating,tranforing,selecting creating better input
#data analysis----> preforming analysis on data based on different factors

#checking duplicates values:
import numpy as np
df.duplicate().sum()
#what if it has dup;icate set of values
df=df.drop_duplicates()

In [1]:
import numpy as np

In [26]:
import pandas as pd

In [22]:

df=pd.read_csv('satya.csv')

In [23]:
df

,student_id,age,gender,city,study_hours,attendance,math_score,science_score,english_score,placement,salary_lpa
0,1,21,M,Hyderabad,2,61,87,57,55,No,0
1,2,18,M,Mumbai,9,65,77,67,42,No,0
2,3,21,F,Mumbai,4,92,78,41,75,No,0
3,4,20,F,Delhi,8,97,57,91,95,Yes,3
4,5,19,M,Chennai,5,69,53,88,61,No,0
...,...,...,...,...,...,...,...,...,...,...,...
95,96,18,M,Hyderabad,5,98,84,96,57,Yes,11
96,97,21,F,Chennai,4,86,71,75,88,No,0
97,98,24,M,Delhi,8,61,45,58,54,No,0
98,99,24,F,Delhi,10,83,70,75,73,Yes,8
99,100,19,M,Delhi,8,77,59,56,54,No,0

In [27]:
import matplotlib.pyplot as plt

In [35]:
df.isnull().sum()

student_id       0
age              0
gender           0
city             0
study_hours      0
attendance       0
math_score       0
science_score    0
english_score    0
placement        0
salary_lpa       0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

In [37]:
df=df.drop_duplicates()

In [46]:
df.isnull().sum()

student_id       0
age              0
gender           0
city             0
study_hours      0
attendance       0
math_score       0
science_score    0
english_score    0
placement        0
salary_lpa       0
dtype: int64

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     100 non-null    int64
 1   age            100 non-null    int64
 2   gender         100 non-null    object
 3   city           100 non-null    object
 4   study_hours    100 non-null    int64
 5   attendance     100 non-null    int64
 6   math_score     100 non-null    int64
 7   science_score  100 non-null    int64
 8   english_score  100 non-null    int64
 9   placement      100 non-null    object
 10  salary_lpa     100 non-null    int64
dtypes: int64(8), object(3)
memory usage: 8.7+ KB

In [48]:
df.shape(15,6)

TypeError: 'tuple' object is not callable

In [51]:
df.isnull().sum()

student_id       0
age              0
gender           0
city             0
study_hours      0
attendance       0
math_score       0
science_score    0
english_score    0
placement        0
salary_lpa       0
dtype: int64

In [52]:
df[df.duplicated()]

Empty DataFrame
Columns: [student_id, age, gender, city, study_hours, attendance, math_score, science_score, english_score, placement, salary_lpa]
Index: []

In [53]:
df.dropna()

,student_id,age,gender,city,study_hours,attendance,math_score,science_score,english_score,placement,salary_lpa
0,1,21,M,Hyderabad,2,61,87,57,55,No,0
1,2,18,M,Mumbai,9,65,77,67,42,No,0
2,3,21,F,Mumbai,4,92,78,41,75,No,0
3,4,20,F,Delhi,8,97,57,91,95,Yes,3
4,5,19,M,Chennai,5,69,53,88,61,No,0
...,...,...,...,...,...,...,...,...,...,...,...
95,96,18,M,Hyderabad,5,98,84,96,57,Yes,11
96,97,21,F,Chennai,4,86,71,75,88,No,0
97,98,24,M,Delhi,8,61,45,58,54,No,0
98,99,24,F,Delhi,10,83,70,75,73,Yes,8
99,100,19,M,Delhi,8,77,59,56,54,No,0