pandas---->panel data
Think of Pandas as Excel + SQL + Python combined.

In [1]:
import pandas as pd

In [3]:
data={
    'name':['satya','ravi','sai','ajay','rahul'],
     "Python":[90,85,78,92,88],
    "SQL":[80,75,85,95,70],
    "ML":[85,90,80,88,92]
}
df=pd.DataFrame(data)
print(df)

    name  Python  SQL  ML
0  satya      90   80  85
1   ravi      85   75  90
2    sai      78   85  80
3   ajay      92   95  88
4  rahul      88   70  92

In [10]:
ages=pd.Series([25,30,22],index=['alica','bob','charlie'])
print(ages)

alica      25
bob        30
charlie    22
dtype: int64

In [11]:
print(ages['bob'])

30

In [13]:
print(ages[ages>25])

bob    30
dtype: int64

In [19]:
sets={ # create a dict — each key is a column name
    'name': ['Alice', 'Bob', 'Charlie'], # column 1 — names as strings
'age': [25, 30, 22], # column 2 — ages as integers
'score': [88.5, 92.0, 76.3] # column 3 — scores as floats
    
}
df=pd.DataFrame(sets)
print(df.shape)
print(df.dtypes)
print(df.head(2))
print(df.describe())# .describe() = count, mean, std, min, max — instant stats summary

(3, 3)
name      object
age        int64
score    float64
dtype: object
    name  age  score
0  Alice   25   88.5
1    Bob   30   92.0
             age      score
count   3.000000   3.000000
mean   25.666667  85.600000
std     4.041452   8.241966
min    22.000000  76.300000
25%    23.500000  82.400000
50%    25.000000  88.500000
75%    27.500000  90.250000
max    30.000000  92.000000

In [26]:

df[['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   22

In [27]:
df[df['age']>24]

    name  age  score
0  Alice   25   88.5
1    Bob   30   92.0

In [30]:
df[df['age']>24]

    name  age  score
0  Alice   25   88.5
1    Bob   30   92.0

In [31]:
df.loc[0,'name']

'Alice'

In [32]:
import numpy as np

In [37]:
df = pd.DataFrame({ # create sample data with missing values
'age': [25, np.nan, 22, 35], # np.nan = 'Not a Number' — standard missing value marker
'score': [88.5, 92.0, np.nan, 76.3] # missing score for 3rd person
})
 
print(df.isnull()) # .isnull() = True/False table — True means that cell is missing
print(df.isnull().sum())

     age  score
0  False  False
1   True  False
2  False   True
3  False  False
age      1
score    1
dtype: int64

In [41]:
df_1 = pd.DataFrame({ # sample student dataset
'city': ['Hyd','Hyd','Delhi','Delhi','Hyd'], # categorical column — the group we want to split by
'score': [88, 92, 76, 85, 70], # numeric column — we'll compute stats on this
'age': [25, 30, 22, 28, 26] # another numeric column
})
df_1.groupby('city')['score'].mean()
df_1.groupby('city')['score'].agg(['mean','max','count'])

            mean  max  count
city
Delhi  80.500000   85      2
Hyd    83.333333   92      3

df["Name"]

Here:

[]

means:

Get column "Name"



df["Name"].head()

Read it as:

Take column "Name"
↓
Run head() function

Easy Memory Trick
[]

👉 Data lives here

[10,20,30]
()

👉 Work happens here

sum([10,20,30])

In Pandas:
df["Age"].mean()

Think:

df
 ↓
["Age"]      ← select column
 ↓
mean()       ← calculate average